"""Golden-fixture loading (design doc §4.4).

Fixtures under tests/fixtures/*_golden.json are generated by running the
*actual* JS logic from Renovation_Planner_v2.html under Node (no browser
needed — the scheduling/cost/materials functions touch no DOM APIs) against
the app's own `seedState()`. See backend/scripts/generate_golden_fixture.js.

  seed_plan_golden.json         — defaults (stage cascade on, no weekends)
  seed_plan_variant_golden.json — work_weekends=True, sequence_stages=False,
                                  plus a fixed start_override on one task

The Python engine must reproduce every number in these fixtures exactly. If
a port ever needs to change, regenerate the fixtures from the HTML app first
and confirm the new numbers are actually correct, don't just edit the JSON.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from renovator.domain.models import Plan, Rate, TaskLine

FIXTURES_DIR = Path(__file__).parent / "fixtures"
GOLDEN_FIXTURE_NAMES = ["seed_plan_golden.json", "seed_plan_variant_golden.json"]


def _plan_from_js_dict(raw: dict) -> Plan:
    settings = raw["settings"]
    rates = [
        Rate(key=r["key"], label=r["label"], unit=r["unit"], value=r["value"])
        for r in raw["rates"]
    ]
    items = [
        TaskLine(
            id=it["id"],
            task_id=it["taskId"],
            room=it["room"],
            name=it["name"],
            category=it["category"],
            line_type=it["lineType"],
            worker_type=it["workerType"] or "",
            phase=it["phase"],
            stage_id=it["stageId"],
            mandatory=it["mandatory"],
            duration_days=it["durationDays"],
            start_override=it["startOverride"],
            depends_on=it["dependsOn"] or [],
            cost_method=it["costMethod"],
            rate_key=it.get("rateKey") or None,
            qty=it.get("qty"),
            custom_amount=it.get("customAmount"),
            buy_status=it["buyStatus"] or "To buy",
            status=it["status"],
            notes=it["notes"] or "",
            actual_cost=it["actualCost"],
        )
        for it in raw["items"]
    ]
    return Plan(
        settings={
            "project_start": settings["projectStart"],
            "work_weekends": settings["workWeekends"],
            "sequence_stages": settings["sequenceStages"],
        },
        rooms=raw["rooms"],
        rates=rates,
        phases=raw["phases"],
        stages=raw["stages"],
        items=items,
    )


@pytest.fixture(params=GOLDEN_FIXTURE_NAMES)
def golden(request) -> dict:
    return json.loads((FIXTURES_DIR / request.param).read_text())


@pytest.fixture()
def golden_plan(golden: dict) -> Plan:
    return _plan_from_js_dict(golden["plan"])
