"""Golden-fixture parity tests (design doc §4.4).

Everything here compares the Python engine's output against
tests/fixtures/seed_plan_golden.json, generated by running the actual JS
from Renovation_Planner_v2.html under Node. See tests/conftest.py.
"""

from __future__ import annotations

from renovator.engine.cost import estimate_summary
from renovator.engine.dependencies import suggested_order
from renovator.engine.materials import materials_plan
from renovator.engine.schedule import compute_schedule, project_end_date
from renovator.engine.tasks import group_by_task


def test_group_by_task_matches_golden(golden_plan, golden):
    py_tasks = {t.task_id: t for t in group_by_task(golden_plan)}
    for expected in golden["tasks"]:
        t = py_tasks[expected["taskId"]]
        assert t.room == expected["room"]
        assert t.name == expected["name"]
        assert t.category == expected["category"]
        assert t.phase == expected["phase"]
        assert t.stage_id == expected["stageId"]
        assert t.mandatory == expected["mandatory"]
        assert t.duration_days == expected["durationDays"]
        assert t.is_split == expected["isSplit"]
        assert t.total_cost == expected["totalCost"]
        assert sorted(l.id for l in t.lines) == sorted(expected["lineIds"])


def test_compute_schedule_matches_golden(golden_plan, golden):
    schedule = compute_schedule(golden_plan)
    expected_sched = golden["schedule"]

    assert schedule.project_start.isoformat() == expected_sched["projectStart"]
    assert project_end_date(schedule).isoformat() == expected_sched["projectEnd"]

    for task_id, expected in expected_sched["tasks"].items():
        actual = schedule.tasks[task_id]
        assert actual.start.isoformat() == expected["start"], task_id
        assert actual.end.isoformat() == expected["end"], task_id
        assert actual.dur == expected["dur"], task_id


def test_estimate_summary_matches_golden(golden_plan, golden):
    summary = estimate_summary(golden_plan)
    expected = golden["estimate"]

    assert summary["total"] == expected["total"]
    assert summary["mandatory"] == expected["mandatory"]
    assert summary["optional"] == expected["optional"]
    assert summary["materials"] == expected["materials"]
    assert [list(kv) for kv in summary["by_room"]] == expected["byRoom"]
    assert [list(kv) for kv in summary["by_trade"]] == expected["byTradeBucketed"]
    assert [list(kv) for kv in summary["by_phase"]] == expected["byPhase"]


def test_materials_plan_matches_golden(golden_plan, golden):
    plan_result = materials_plan(golden_plan)
    expected = golden["materialsPlan"]

    assert plan_result.total == expected["total"]
    assert plan_result.to_buy_cost == expected["toBuyCost"]
    assert plan_result.to_buy_count == expected["toBuyCount"]
    assert plan_result.ordered_count == expected["ordered"]
    assert plan_result.delivered_count == expected["delivered"]

    by_line_id = {r.line.id: r for r in plan_result.lines}
    for exp_line in expected["lines"]:
        actual = by_line_id[exp_line["lineId"]]
        assert (actual.need_by.isoformat() if actual.need_by else None) == exp_line["needBy"]
        assert actual.qty == exp_line["qty"]
        assert actual.unit == exp_line["unit"]
        assert actual.cost == exp_line["cost"]


def test_suggested_order_matches_golden(golden_plan, golden):
    order = suggested_order(golden_plan)
    assert [it.id for it in order] == [it["id"] for it in golden["suggestedOrder"]]
